[program:device-server]
directory=/data/demo-open.tangeai.cn/device-server
command=/data/demo-open.tangeai.cn/device-server/device-server -c /data/demo-open.tangeai.cn/device-server/config.yaml
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=15
environment=GIN_MODE="release",SERVICE_INSTANCE_ID="device-server-001"
stderr_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stdout_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
user=root
stopasgroup=true
killasgroup=true

[program:user-server]
directory=/data/demo-open.tangeai.cn/user-server
command=/data/demo-open.tangeai.cn/user-server/user-server -c /data/demo-open.tangeai.cn/user-server/config.yaml
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=15
environment=GIN_MODE="release",SERVICE_INSTANCE_ID="user-server-001"
stderr_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stdout_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
user=root
stopasgroup=true
killasgroup=true

[program:voip-server]
directory=/data/demo-open.tangeai.cn/voip-server
command=/data/demo-open.tangeai.cn/voip-server/voip-server -c /data/demo-open.tangeai.cn/voip-server/config.yaml
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=15
environment=GIN_MODE="release",SERVICE_INSTANCE_ID="voip-server-001"
stderr_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stdout_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
user=root
stopasgroup=true
killasgroup=true

[program:ai-server]
directory=/data/demo-open.tangeai.cn/ai-server
command=/data/demo-open.tangeai.cn/ai-server/ai-server -c /data/demo-open.tangeai.cn/ai-server/config.yaml
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=15
environment=GIN_MODE="release",SERVICE_INSTANCE_ID="ai-server-001"
stderr_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stdout_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
user=root
stopasgroup=true
killasgroup=true

[program:call-server]
directory=/data/demo-open.tangeai.cn/call-server
command=/data/demo-open.tangeai.cn/call-server/call-server -c /data/demo-open.tangeai.cn/call-server/config.yaml
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=15
environment=GIN_MODE="release",SERVICE_INSTANCE_ID="call-server-001"
stderr_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stdout_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
user=root
stopasgroup=true
killasgroup=true

[program:admin-server]
directory=/data/demo-open.tangeai.cn/admin-server
command=/data/demo-open.tangeai.cn/admin-server/admin-server -c /data/demo-open.tangeai.cn/admin-server/config.yaml
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=15
environment=GIN_MODE="release",SERVICE_INSTANCE_ID="admin-server-001"
stderr_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stdout_logfile=/data/demo-open.tangeai.cn/logs/%(program_name)s.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
user=root
stopasgroup=true
killasgroup=true

[group:demo-open]
programs=device-server,user-server,voip-server,ai-server,call-server,admin-server
