CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE users ADD COLUMN bind_quota INT NOT NULL DEFAULT 10 COMMENT '剩余可绑额度';
ALTER TABLE users ADD COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1=active 0=disabled';
ALTER TABLE users ADD COLUMN disabled_at DATETIME NULL;
ALTER TABLE users ADD COLUMN auth_revision BIGINT NOT NULL DEFAULT 1 COMMENT '密码或账号状态变更时递增';
