-- 为既有业务表补齐 MySQL 元数据注释；字段定义保持与当前 schema 完全一致。
ALTER TABLE schema_migrations
    COMMENT = 'ThingConnect 数据库迁移版本台账',
    MODIFY COLUMN component VARCHAR(64) NOT NULL COMMENT '迁移组件名：core 或 admin',
    MODIFY COLUMN version BIGINT NOT NULL COMMENT '组件迁移版本号',
    MODIFY COLUMN applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '迁移完成时间';

ALTER TABLE users
    COMMENT = '业务用户账号',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户主键',
    MODIFY COLUMN email VARCHAR(255) NOT NULL COMMENT '登录邮箱，系统内唯一',
    MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '密码哈希，不存储明文',
    MODIFY COLUMN bind_quota INT NOT NULL DEFAULT 10 COMMENT '剩余可绑定设备额度',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '账号状态：1=启用，0=禁用',
    MODIFY COLUMN disabled_at DATETIME NULL COMMENT '账号禁用时间',
    MODIFY COLUMN auth_revision BIGINT NOT NULL DEFAULT 1 COMMENT '认证版本；密码或账号状态变化时递增',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE device_pool
    COMMENT = '可分配设备凭据池',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备池记录主键',
    MODIFY COLUMN device_id VARCHAR(64) NOT NULL COMMENT '设备业务标识，系统内唯一',
    MODIFY COLUMN device_key VARCHAR(64) NOT NULL COMMENT '设备接入密钥',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 0 COMMENT '分配状态：0=未分配，1=已分配',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入或创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE device_bind
    COMMENT = '设备当前身份、归属和绑定状态',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备绑定记录主键',
    MODIFY COLUMN device_id VARCHAR(64) NOT NULL COMMENT '设备业务标识',
    MODIFY COLUMN mac VARCHAR(32) NOT NULL DEFAULT '' COMMENT '设备 MAC 地址',
    MODIFY COLUMN chip_uid VARCHAR(128) NOT NULL DEFAULT '' COMMENT '芯片唯一标识',
    MODIFY COLUMN device_rand VARCHAR(64) NOT NULL DEFAULT '' COMMENT '设备端维护的稳定随机标识',
    MODIFY COLUMN assign VARCHAR(16) NOT NULL DEFAULT '' COMMENT '分配方式：dynamic=设备池分配，preburn=出厂预烧',
    MODIFY COLUMN device_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前绑定用户设置的设备名称，解绑时清空',
    MODIFY COLUMN user_id BIGINT NOT NULL DEFAULT 0 COMMENT '当前绑定用户主键；0 表示未绑定',
    MODIFY COLUMN last_user_id BIGINT NOT NULL DEFAULT 0 COMMENT '最近一次绑定用户主键',
    MODIFY COLUMN active_time DATETIME NULL COMMENT '设备首次或最近激活时间',
    MODIFY COLUMN bind_time DATETIME NULL COMMENT '当前绑定建立时间',
    MODIFY COLUMN unbind_time DATETIME NULL COMMENT '最近一次解绑时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN mac_user_key VARCHAR(64) AS (IF(mac='' OR user_id=0, NULL, CONCAT(mac, ':', user_id))) STORED COMMENT '当前用户与 MAC 的唯一约束键';

ALTER TABLE device_bind_log
    COMMENT = '设备绑定与解绑历史',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '绑定日志主键',
    MODIFY COLUMN device_id VARCHAR(64) NOT NULL COMMENT '设备业务标识',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '执行绑定或解绑的用户主键',
    MODIFY COLUMN action TINYINT NOT NULL COMMENT '动作：1=绑定，2=解绑',
    MODIFY COLUMN mac VARCHAR(32) NOT NULL DEFAULT '' COMMENT '动作发生时的 MAC 地址快照',
    MODIFY COLUMN chip_uid VARCHAR(128) NOT NULL DEFAULT '' COMMENT '动作发生时的芯片标识快照',
    MODIFY COLUMN device_rand VARCHAR(64) NOT NULL DEFAULT '' COMMENT '动作发生时的设备随机标识快照',
    MODIFY COLUMN assign VARCHAR(16) NOT NULL DEFAULT '' COMMENT '分配方式：dynamic=设备池分配，preburn=出厂预烧',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '动作发生时间';

ALTER TABLE cleanup_outbox
    COMMENT = '设备解绑后跨服务清理事务发件箱',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发件箱任务主键',
    MODIFY COLUMN device_id VARCHAR(64) NOT NULL COMMENT '待清理设备业务标识',
    MODIFY COLUMN target VARCHAR(32) NOT NULL COMMENT '目标服务或清理类型',
    MODIFY COLUMN attempts INT NOT NULL DEFAULT 0 COMMENT '已执行次数',
    MODIFY COLUMN next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次允许执行时间',
    MODIFY COLUMN last_error VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '最近一次失败摘要',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE call_contact
    COMMENT = '设备之间的通话联系人关系',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '联系人关系主键',
    MODIFY COLUMN device_id_a VARCHAR(64) NOT NULL COMMENT '字典序较小的设备标识',
    MODIFY COLUMN device_id_b VARCHAR(64) NOT NULL COMMENT '字典序较大的设备标识',
    MODIFY COLUMN source VARCHAR(8) NOT NULL DEFAULT 'manual' COMMENT '关系来源：auto=同账号自动建立，manual=跨账号手工建立',
    MODIFY COLUMN initiator CHAR(1) NOT NULL DEFAULT 'a' COMMENT '手工关系发起方：a 或 b',
    MODIFY COLUMN user_id_a BIGINT NOT NULL COMMENT '设备 A 对应用户主键',
    MODIFY COLUMN user_id_b BIGINT NOT NULL COMMENT '设备 B 对应用户主键',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '关系状态：0=待接受，1=已接受，2=已拒绝，3=已删除',
    MODIFY COLUMN remark_a VARCHAR(64) NOT NULL DEFAULT '' COMMENT '设备 A 一侧看到的联系人备注',
    MODIFY COLUMN remark_b VARCHAR(64) NOT NULL DEFAULT '' COMMENT '设备 B 一侧看到的联系人备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '关系创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE voip_device_profile
    COMMENT = '设备 VoIP 媒体参数',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备媒体资料主键',
    MODIFY COLUMN device_id VARCHAR(20) NOT NULL COMMENT '设备业务标识',
    MODIFY COLUMN profile VARCHAR(512) NOT NULL COMMENT 'JSON 格式的媒体参数',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE voip_device_auth
    COMMENT = '微信用户对设备的 VoIP 授权',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备授权主键',
    MODIFY COLUMN device_id VARCHAR(20) NOT NULL COMMENT '被授权设备业务标识',
    MODIFY COLUMN wx_open_id VARCHAR(64) NOT NULL COMMENT '微信用户 OpenID',
    MODIFY COLUMN wx_app_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信小程序 AppID',
    MODIFY COLUMN wx_model_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信设备型号标识',
    MODIFY COLUMN remark VARCHAR(64) NOT NULL DEFAULT '' COMMENT '联系人备注快照',
    MODIFY COLUMN authorized_device_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '最近一次微信授权时的设备名称快照',
    MODIFY COLUMN auth_status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '授权状态：active=有效，invalid=失效',
    MODIFY COLUMN invalid_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT '授权失效原因码',
    MODIFY COLUMN invalid_at DATETIME NULL COMMENT '授权失效时间',
    MODIFY COLUMN last_verified_at DATETIME NULL COMMENT '最近一次向微信侧验证时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权创建时间';

ALTER TABLE voip_user_profile
    COMMENT = '微信用户统一 VoIP 联系人资料',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户资料主键',
    MODIFY COLUMN wx_open_id VARCHAR(64) NOT NULL COMMENT '微信用户 OpenID',
    MODIFY COLUMN wx_app_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信小程序 AppID',
    MODIFY COLUMN remark VARCHAR(64) NOT NULL DEFAULT '' COMMENT '该 OpenID 在所有设备联系人列表中的统一备注',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE ai_user_role
    COMMENT = '用户绑定的探鸽云端 AI 角色',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户角色关系主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '业务用户主键',
    MODIFY COLUMN role_id VARCHAR(64) NOT NULL COMMENT '探鸽云端角色标识',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '绑定时间';

ALTER TABLE ai_device_role
    COMMENT = '设备绑定的探鸽云端 AI 角色',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备角色关系主键',
    MODIFY COLUMN device_id VARCHAR(64) NOT NULL COMMENT '设备业务标识',
    MODIFY COLUMN role_id VARCHAR(64) NOT NULL COMMENT '探鸽云端角色标识',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '执行绑定的业务用户主键',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '绑定时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE ai_user_resource
    COMMENT = '用户可使用的探鸽云端 AI 资源',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户资源关系主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '业务用户主键',
    MODIFY COLUMN type VARCHAR(32) NOT NULL COMMENT '资源类型：mcp、device_plugin、kb 或 kb_file',
    MODIFY COLUMN resource_id VARCHAR(64) NOT NULL COMMENT '探鸽云端资源标识',
    MODIFY COLUMN name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '资源展示名称快照，云端改名时刷新',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '绑定时间';
