-- 版本 1 Admin 表的 MySQL 元数据注释；字段定义保持与建表基线完全一致。
ALTER TABLE admin_users
    COMMENT = '后台管理员账号',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '管理员主键',
    MODIFY COLUMN email VARCHAR(255) NOT NULL COMMENT '管理员登录邮箱，系统内唯一',
    MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '密码哈希，不存储明文',
    MODIFY COLUMN nick_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '管理员显示名称',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '账号状态：1=启用，0=禁用',
    MODIFY COLUMN auth_revision BIGINT NOT NULL DEFAULT 1 COMMENT '认证版本；安全属性变化时递增并撤销旧会话',
    MODIFY COLUMN must_change_password TINYINT NOT NULL DEFAULT 0 COMMENT '是否要求下次登录修改密码：1=是，0=否',
    MODIFY COLUMN password_updated_at DATETIME NULL COMMENT '最近一次修改密码时间',
    MODIFY COLUMN last_login_ip VARCHAR(45) NOT NULL DEFAULT '' COMMENT '最近一次成功登录客户端 IP',
    MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最近一次成功登录时间',
    MODIFY COLUMN remark VARCHAR(256) NOT NULL DEFAULT '' COMMENT '管理员备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_roles
    COMMENT = '后台 RBAC 角色',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '稳定角色编码，系统内唯一',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '角色显示名称',
    MODIFY COLUMN parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父角色主键；0 表示无父角色',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '同级展示顺序',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '角色状态：1=启用，0=禁用',
    MODIFY COLUMN remark VARCHAR(256) NOT NULL DEFAULT '' COMMENT '角色备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_user_roles
    COMMENT = '管理员与角色的多对多关系',
    MODIFY COLUMN admin_user_id BIGINT NOT NULL COMMENT '管理员主键',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色主键',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权时间';

ALTER TABLE admin_role_permissions
    COMMENT = '角色直接拥有的权限码',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色主键',
    MODIFY COLUMN permission_code VARCHAR(64) NOT NULL COMMENT '稳定权限编码',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权时间';

ALTER TABLE admin_menus
    COMMENT = '后台导航菜单定义',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '菜单主键',
    MODIFY COLUMN parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父菜单主键；0 表示顶级菜单',
    MODIFY COLUMN menu_code VARCHAR(64) NOT NULL COMMENT '稳定菜单编码，系统内唯一',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '菜单显示名称',
    MODIFY COLUMN icon VARCHAR(64) NOT NULL DEFAULT '' COMMENT '前端图标标识',
    MODIFY COLUMN path VARCHAR(128) NOT NULL DEFAULT '' COMMENT '前端路由路径',
    MODIFY COLUMN permission_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '访问菜单要求的权限码',
    MODIFY COLUMN menu_type TINYINT NOT NULL DEFAULT 2 COMMENT '菜单类型：1=目录，2=页面',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '同级展示顺序',
    MODIFY COLUMN visible TINYINT NOT NULL DEFAULT 1 COMMENT '是否在导航中显示：1=显示，0=隐藏',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '菜单状态：1=启用，0=禁用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_role_menus
    COMMENT = '角色可见菜单关系',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色主键',
    MODIFY COLUMN menu_id BIGINT NOT NULL COMMENT '菜单主键',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权时间';

ALTER TABLE admin_sessions
    COMMENT = '管理员刷新令牌会话',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '会话主键',
    MODIFY COLUMN admin_user_id BIGINT NOT NULL COMMENT '管理员主键',
    MODIFY COLUMN family_id CHAR(36) NOT NULL COMMENT '刷新令牌轮换族标识',
    MODIFY COLUMN token_hash CHAR(64) NOT NULL COMMENT '刷新令牌 SHA-256 哈希',
    MODIFY COLUMN replaced_by_id BIGINT NOT NULL DEFAULT 0 COMMENT '轮换后替代本会话的新会话主键',
    MODIFY COLUMN expires_at DATETIME NOT NULL COMMENT '刷新会话过期时间',
    MODIFY COLUMN revoked_at DATETIME NULL COMMENT '会话撤销时间',
    MODIFY COLUMN revoked_reason VARCHAR(128) NOT NULL DEFAULT '' COMMENT '会话撤销原因码或摘要',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '会话创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_mfa_factors
    COMMENT = '管理员多因素认证因子',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'MFA 因子主键',
    MODIFY COLUMN admin_user_id BIGINT NOT NULL COMMENT '管理员主键',
    MODIFY COLUMN factor_type VARCHAR(16) NOT NULL DEFAULT 'totp' COMMENT '因子类型，当前为 totp',
    MODIFY COLUMN secret_enc TEXT NOT NULL COMMENT '使用配置加密密钥加密后的 TOTP 密钥',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 0 COMMENT '因子状态：0=待确认，1=已启用',
    MODIFY COLUMN last_used_step BIGINT NOT NULL DEFAULT 0 COMMENT '最近使用的 TOTP 时间步，用于防重放',
    MODIFY COLUMN confirmed_at DATETIME NULL COMMENT '因子确认启用时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_mfa_recovery_codes
    COMMENT = '管理员 MFA 一次性恢复码',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '恢复码主键',
    MODIFY COLUMN admin_user_id BIGINT NOT NULL COMMENT '管理员主键',
    MODIFY COLUMN code_hash CHAR(64) NOT NULL COMMENT '恢复码哈希，不存储明文',
    MODIFY COLUMN used_at DATETIME NULL COMMENT '恢复码使用时间；空表示未使用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间';

ALTER TABLE admin_login_log
    COMMENT = '管理员登录审计日志',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '登录日志主键',
    MODIFY COLUMN admin_user_id BIGINT NOT NULL DEFAULT 0 COMMENT '管理员主键；无法识别时为 0',
    MODIFY COLUMN email VARCHAR(255) NOT NULL DEFAULT '' COMMENT '登录请求提交的邮箱快照',
    MODIFY COLUMN client_ip VARCHAR(45) NOT NULL DEFAULT '' COMMENT '客户端 IP',
    MODIFY COLUMN user_agent VARCHAR(512) NOT NULL DEFAULT '' COMMENT '客户端 User-Agent',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '登录结果：1=成功，0=失败',
    MODIFY COLUMN message VARCHAR(512) NOT NULL DEFAULT '' COMMENT '登录结果说明或失败摘要',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录发生时间';

ALTER TABLE admin_dict_types
    COMMENT = '后台数据字典类型',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '字典类型主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '稳定字典类型编码，系统内唯一',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '字典类型显示名称',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '字典类型状态：1=启用，0=禁用',
    MODIFY COLUMN remark VARCHAR(256) NOT NULL DEFAULT '' COMMENT '字典类型备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_dict_items
    COMMENT = '后台数据字典项',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '字典项主键',
    MODIFY COLUMN dict_type_code VARCHAR(64) NOT NULL COMMENT '所属字典类型编码',
    MODIFY COLUMN label VARCHAR(128) NOT NULL COMMENT '字典项显示文本',
    MODIFY COLUMN value VARCHAR(128) NOT NULL COMMENT '字典项稳定值',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '展示顺序',
    MODIFY COLUMN is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否为默认项：1=是，0=否',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '字典项状态：1=启用，0=禁用',
    MODIFY COLUMN extra VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '扩展 JSON 或附加文本',
    MODIFY COLUMN remark VARCHAR(256) NOT NULL DEFAULT '' COMMENT '字典项备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_audit_log
    COMMENT = '后台管理操作审计日志',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '审计日志主键',
    MODIFY COLUMN admin_user_id BIGINT NOT NULL DEFAULT 0 COMMENT '操作管理员主键；无法识别时为 0',
    MODIFY COLUMN role_codes VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '操作时管理员角色编码快照',
    MODIFY COLUMN request_id VARCHAR(64) NOT NULL COMMENT '请求链路标识',
    MODIFY COLUMN method VARCHAR(8) NOT NULL DEFAULT '' COMMENT 'HTTP 方法',
    MODIFY COLUMN path VARCHAR(255) NOT NULL DEFAULT '' COMMENT '请求路径',
    MODIFY COLUMN http_status INT NOT NULL DEFAULT 0 COMMENT 'HTTP 响应状态码',
    MODIFY COLUMN latency_ms BIGINT NOT NULL DEFAULT 0 COMMENT '请求耗时毫秒数',
    MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '稳定审计动作码',
    MODIFY COLUMN resource_type VARCHAR(64) NOT NULL COMMENT '被操作资源类型',
    MODIFY COLUMN resource_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '被操作资源标识',
    MODIFY COLUMN reason VARCHAR(512) NOT NULL DEFAULT '' COMMENT '操作原因或备注',
    MODIFY COLUMN before_value TEXT NULL COMMENT '操作前数据快照',
    MODIFY COLUMN after_value TEXT NULL COMMENT '操作后数据快照',
    MODIFY COLUMN client_ip VARCHAR(45) NOT NULL DEFAULT '' COMMENT '客户端 IP',
    MODIFY COLUMN user_agent VARCHAR(512) NOT NULL DEFAULT '' COMMENT '客户端 User-Agent',
    MODIFY COLUMN success TINYINT NOT NULL DEFAULT 1 COMMENT '操作结果：1=成功，0=失败',
    MODIFY COLUMN error_message VARCHAR(512) NOT NULL DEFAULT '' COMMENT '失败原因的脱敏摘要',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作发生时间';

ALTER TABLE admin_jobs
    COMMENT = '后台异步任务',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务主键',
    MODIFY COLUMN job_type VARCHAR(64) NOT NULL COMMENT '稳定任务类型编码',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 0 COMMENT '任务状态：0=待执行，1=执行中，2=成功，3=部分成功，4=失败',
    MODIFY COLUMN source_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户提交的源文件名',
    MODIFY COLUMN input_file VARCHAR(512) NOT NULL DEFAULT '' COMMENT '任务输入文件相对路径',
    MODIFY COLUMN result_file VARCHAR(512) NOT NULL DEFAULT '' COMMENT '任务结果文件相对路径',
    MODIFY COLUMN total_count INT NOT NULL DEFAULT 0 COMMENT '任务总条目数',
    MODIFY COLUMN succeeded_count INT NOT NULL DEFAULT 0 COMMENT '成功条目数',
    MODIFY COLUMN failed_count INT NOT NULL DEFAULT 0 COMMENT '失败条目数',
    MODIFY COLUMN attempts INT NOT NULL DEFAULT 0 COMMENT '任务领取执行次数',
    MODIFY COLUMN next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次允许领取时间',
    MODIFY COLUMN started_at DATETIME NULL COMMENT '最近一次开始执行时间',
    MODIFY COLUMN worker_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前持有任务租约的工作实例标识',
    MODIFY COLUMN lease_until DATETIME NULL COMMENT '当前工作实例租约到期时间',
    MODIFY COLUMN finished_at DATETIME NULL COMMENT '任务最终完成时间',
    MODIFY COLUMN last_error VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '最近一次任务失败摘要',
    MODIFY COLUMN created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建任务的管理员主键',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE admin_job_items
    COMMENT = '后台异步任务逐条处理结果',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务条目主键',
    MODIFY COLUMN job_id BIGINT NOT NULL COMMENT '所属任务主键',
    MODIFY COLUMN row_no INT NOT NULL COMMENT '源文件中的行号',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 0 COMMENT '条目状态：0=待处理，1=成功，2=失败',
    MODIFY COLUMN resource_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '处理成功后产生或关联的资源标识',
    MODIFY COLUMN error_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '稳定失败原因码',
    MODIFY COLUMN error_message VARCHAR(512) NOT NULL DEFAULT '' COMMENT '失败原因的脱敏说明',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '条目创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE config_entries
    COMMENT = 'Admin 动态配置发布记录',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '配置记录主键',
    MODIFY COLUMN namespace VARCHAR(64) NOT NULL COMMENT '配置命名空间',
    MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '命名空间内的配置键',
    MODIFY COLUMN scope_type VARCHAR(16) NOT NULL DEFAULT 'global' COMMENT '配置范围类型，当前为 global',
    MODIFY COLUMN scope_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '配置范围标识；global 范围为空',
    MODIFY COLUMN value TEXT NOT NULL COMMENT '不含密钥字段的配置 JSON',
    MODIFY COLUMN secret_value TEXT NULL COMMENT '密钥字段配置 JSON 明文；依赖数据库访问控制保护',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '配置状态：1=启用，0=禁用',
    MODIFY COLUMN revision BIGINT NOT NULL DEFAULT 1 COMMENT '配置修订号，用于并发控制和运行时应用',
    MODIFY COLUMN updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '最近发布配置的管理员主键',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后发布时间';

ALTER TABLE config_publish_outbox
    COMMENT = '动态配置发布事务发件箱',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发件箱事件主键',
    MODIFY COLUMN config_entry_id BIGINT NOT NULL COMMENT '对应配置记录主键',
    MODIFY COLUMN revision BIGINT NOT NULL COMMENT '本次发布的配置修订号',
    MODIFY COLUMN event_type VARCHAR(32) NOT NULL DEFAULT 'config.updated' COMMENT '稳定事件类型',
    MODIFY COLUMN attempts INT NOT NULL DEFAULT 0 COMMENT '投递尝试次数',
    MODIFY COLUMN next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次允许投递时间',
    MODIFY COLUMN delivered_at DATETIME NULL COMMENT '成功投递时间',
    MODIFY COLUMN last_error VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '最近一次投递失败摘要',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事件创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE thingconnect_installation_state
    COMMENT = 'ThingConnect 安装所有权和恢复状态',
    MODIFY COLUMN id TINYINT NOT NULL COMMENT '单例记录主键，固定为 1',
    MODIFY COLUMN product VARCHAR(64) NOT NULL COMMENT '产品标识，固定为 thingconnect',
    MODIFY COLUMN instance_id CHAR(36) NOT NULL COMMENT '部署实例唯一标识',
    MODIFY COLUMN operation_id CHAR(36) NOT NULL COMMENT '首次安装任务唯一标识',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '安装状态：installing、migration_only 或 installed',
    MODIFY COLUMN stage VARCHAR(64) NOT NULL COMMENT '安装或配置激活阶段',
    MODIFY COLUMN generation BIGINT NOT NULL DEFAULT 1 COMMENT '安装状态代次',
    MODIFY COLUMN config_digest CHAR(64) NOT NULL DEFAULT '' COMMENT '已提交配置 revision 的 SHA-256 摘要',
    MODIFY COLUMN last_error_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '最近一次可恢复失败的诊断码',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '实例领取数据库时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '安装状态最后更新时间';
